all: server client server_mod client_mod readme

server:
	g++ -std=c++11 server.cpp -o server

client:
    g++ -std=c++11 client.cpp -o client

server_mod:
	g++ -std=c++11 server.cpp -o server_mod

client_mod:
	g++ -std=c++11 client_mod.cpp -o client_mod

readme:
	cat readme.txt



